# Twitter API Credentials
API_KEY = "iqzJnsCOAX5VYEVQIoWimF5P9"
API_SECRET = "h4jgjCnOmQfRJ1IY1BprU6rd0Y524B2VngRSjGdAmbwivWqJba"
ACCESS_TOKEN = "1589828451652902913-YZnJsYielwXjFg86f4kUf617rd6JG4"
ACCESS_SECRET = "fG4ME1aWriDb1ZX0OKI8lagiagh9tJIwZJZQUd6bq56ur"

# Streamlit App URL (Optional, but useful)
APP_URL = "https://z1assignment-i2gesblxgpvc4zrtdh6rtb.streamlit.app/"
